### ISSUE TITLE
Um registro não deve ser inserido se houver outro registro com a mesma matrícula na lista duplamente encadeada.

### ISSUE THREAD

**Issue by FormigTeen** [GregorySantos/TrabEDA2017.1#15]

**Comment by GregorySantos** [comment]
Isso pode ser feito usando a função de busca antes da inserção, ou vocês pensam em algo melhor?

**Comment by FormigTeen** [comment]
Sim, eu pensei nisso também... Tipo a busca dará a posição melhor para ser inserido ordenado... E depois a posição é passado a inserção, se na posição o valor é igual a inserção é cancelada... se não, ela continua.

**Comment by FormigTeen** [comment]
Será que é bom fazer assim? Eu fiz assim na minha lista da atividade...

**Comment by GregorySantos** [comment]
```
//parte da inserção já existente
 NodeList *previous, *current = L->next;
 while(current != NULL && current->data->matricula < NewNode->data->matricula){ 
            previous = current;
            current = current->next;
        }
// acrescentar isso na inserção
if( current->data->matricula == NewNode->data->matricula) 
      return 0;
```
Acho que só esse acréscimo na função de inserção já resolve. O que você acha?
Assim não precisa ficar chamando a busca cada vez que for inserir.
