### ISSUE TITLE
O usuário pode escolher qual TAD será modificado ou exibido no programa após a importação.

### ISSUE THREAD

**Issue by FormigTeen** [GregorySantos/TrabEDA2017.1#19]

**Comment by GregorySantos** [comment]
Isso significa que o usuário vai escolher **na execução** se quer usar uma lista ou uma árvore?

**Comment by FormigTeen** [comment]
Sim, acredito que depois da importação, o usuário irá escolher o que deseja fazer e em qual TAD ele deseja realizar a operação... Tipo: Visualizar, Excluir, Adicionar, Buscar... Em qual TAD?
