### ISSUE TITLE
A Função BreakLine deve criar a Estrutura Data. 

### ISSUE THREAD

**Issue by FormigTeen** [GregorySantos/TrabEDA2017.1#33]
A Função BreakLine separa os dados da linha, porém não está jogando os dados em alguma estrutura Data... Essa funcionalidade deve ser implementada.

**Comment by FormigTeen** [comment]
@LucasNBP e @GregorySantos , preciso que testem essa Branch para verificar se é o meu computador que tem uma execução bugada... No meu computador, ele está limitando o número de mallocs que o programa pode fazer, vejam se o programa roda de boa no computador de vocês nessa versão.

**Comment by GregorySantos** [comment]
Atualiza essa branch com a master, aqui deu erro porque o Insert antigo tava errado.

**Comment by FormigTeen** [comment]
@GregorySantos , Atualizada!

**Comment by FormigTeen** [comment]
Veja se o seu erro é igual a esse:

<code>
a.out: malloc.c:2369: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.
Aborted (core dumped)
</code>

**Comment by GregorySantos** [comment]
Tá printando só o primeiro registro e então o programa trava. Como que eu vejo isso? Tô usando gcc no windows e não passa essa informação toda.

**Comment by FormigTeen** [comment]
Não sei, dá outro update aí nessa Branch que fiz outra mesclagem. No meu ele trava no 631.

**Comment by FormigTeen** [comment]
![screenshot from 2017-08-18 22-00-22](https://user-images.githubusercontent.com/18594451/29482075-adccdcbc-8460-11e7-898a-a38144c011fd.png)
Aqui está o momento que ele para no meu Terminal.

**Comment by GregorySantos** [comment]
Continua travando no primeiro aqui. Estou escolhendo 1 - Importar Arquivo CSV, entrando com MOCK_DATA.csv, e 1 - Lista Duplamente Encadeada. Não é assim?

**Comment by FormigTeen** [comment]
@GregorySantos , Uhhuuuuu!!!! Resolvi o Bug... Na biblioteca String de C, há um bug da função strcpy onde ele pode copiar também 2 char '\0'... Isso fazia estourar o espaço que eu alocava... Então substituir para strncpy!

**Comment by GregorySantos** [comment]
Quando atualizar avisa aí pra eu testar aqui.

**Comment by FormigTeen** [comment]
Essa issue é fundamental para poder alimentar as Estruturas, tenta fazer o Insert depois que o #40 for aceito... Amanhã de manhã vejo se termino a próxima issue que assinar.

**Comment by GregorySantos** [comment]
Agora rodou até o 1000 :) Só vi um probleminha, quando eu escolho a opção 5 pra sair ele diz que o comando é inválido.

**Comment by FormigTeen** [comment]
@GregorySantos , Validação Corrigida!
