### ISSUE TITLE
Bug Detectado!!!! Ponteiros soltos na memória

### ISSUE THREAD

**Issue by FormigTeen** [GregorySantos/TrabEDA2017.1#42]
https://github.com/GregorySantos/TrabEDA2017.1/blob/4b542c4334063aa300cb83cc8c12b4ef2c44fff3/App/Index.c#L302

A remoção de Node da Lista deve dar free em cada ponteiro do DataNode e também free no próprio DataNode com outra função. Isso aqui irá gerar um Bug Gravíssimo

**Comment by GregorySantos** [comment]
Você quer dizer que ao remover um node tem que remover o datanode que alimentou esse node, e todos os seus ponteiros de char?

**Comment by FormigTeen** [comment]
Sim

**Comment by GregorySantos** [comment]
Se puder dá uma olhada nessa branch que eu abri e me diz se o que eu fiz faz algum sentido hehehe

**Comment by FormigTeen** [comment]
Acho que falta o nome, sobrenome

**Comment by FormigTeen** [comment]
Tudo que é usado malloc para ter ponteiro

**Comment by GregorySantos** [comment]
Mas tem ali free no nome e no sobrenome.

**Comment by FormigTeen** [comment]
É isso mesmo mas é melhor criar uma função agora no Header Data que recebe um datanode e ela faz o remove

**Comment by FormigTeen** [comment]
Depois essa sua função só remove o node list

**Comment by GregorySantos** [comment]
Tipo assim?

```
FreeDataNode(Datanode *D){
     free(nome);
     free(sobrenome);
     free(email);
     free(telefone);
}
```

**Comment by FormigTeen** [comment]
Sim, e o free também no D.

**Comment by GregorySantos** [comment]
Verdade, esqueci o D. E vai chamar esse função onde? No remove?

**Comment by FormigTeen** [comment]
Acho que sim, não sei... Você coloca essa função no Header de Data... E no seu Header de List você terá que utilizar ela na hora de remover o Nó da Lista

**Comment by GregorySantos** [comment]
Então lá na função de remove eu coloco:

```
FreeDataNode(node->data);
free(node);
```

É isso?

**Comment by FormigTeen** [comment]
Acho que sim.
