### ISSUE TITLE
Os dados do CSV devem ser inseridos na Lista duplamente encadeada.

### ISSUE THREAD

**Issue by FormigTeen** [GregorySantos/TrabEDA2017.1#5]

**Comment by FormigTeen** [comment]
Mano, terminou o seu algoritmo??? Preciso dele para fazer a exclusão... @GregorySantos

**Comment by FormigTeen** [comment]
Essa issue ainda não foi resolvida, a Estrutura Data não está sendo criada ao ler cada linha do arquivo.

**Comment by FormigTeen** [comment]
Se liga, agora que fiz o BreakLine retornar DataNode, você terá que pensar em algo para receber esses DataNode e linkar com Node da Lista quando o usuario quiser inserir em Ambas ou só na Lista... Vou assinar a Issue #22, e se quiser, depois de terminar a importação faz logo a inserção individual.

**Comment by GregorySantos** [comment]
Cara, fiquei aqui batendo cabeça pra tentar fazer uma função usando o tal do ponteiro void, de forma que pudesse utilizar ela tanto pra lista quanto pra árvore, mas não consegui fazer funcionar. Só tá indo separado mesmo, e não tô convencido de que está eficiente. Se puder dá uma olhada na branch e diz o que acha.

**Comment by FormigTeen** [comment]
Beleza, vou olhar
