### ISSUE TITLE
A biblioteca List deve conter função showAll da Lista Implementada

### ISSUE THREAD

**Issue by FormigTeen** [GregorySantos/TrabEDA2017.1#62]
@GregorySantos , precisamos de uma função interna da Lista que saia imprimindo de forma organizada cada dado da Lista. Consegue implementar isso? Eu já posso fazer imprimir individualmente porque tem a função de busca, mas tem que ter a opção de exibir todos.

**Comment by GregorySantos** [comment]
Ok, vou tentar aqui

**Comment by GregorySantos** [comment]
Só uma dúvida, você acha melhor imprimir só os dados assim:

1
José Silva
josesilva@mlsksl
3333-4444
23345.22

ou é melhor colocar assim:

Matricula: 1
Nome: José Silva
email: josesilva@mlsksl
Telefone: 3333-4444
Salario: 23345.22

**Comment by FormigTeen** [comment]
Acho o segundo mais bonito

**Comment by FormigTeen** [comment]
Vou seguir o seu padrão, e nas funções de List.h

**Comment by FormigTeen** [comment]
Coloca List no final só para sinalizar no código tipo : showAllList
