### ISSUE TITLE
Bug Detectado!!!! Ponteiros Descartados!!!!

### ISSUE THREAD

**Issue by FormigTeen** [GregorySantos/TrabEDA2017.1#64]
https://github.com/GregorySantos/TrabEDA2017.1/blob/12556488a3d46356077d753e1a0c631069c82d9b/App/Headers/List.h#L56

Deve haver uma função de InsertSafeList.... Quando Unissex chama a ação de Insert implementada no List.h, tem perigo da matrícula existir na lista... Logo o Node criado para inserir na Lista deve ser Destruido e não perdido. 

Qual a melhor solução? Inserir uma Função Safe em em List.h ou tratar a Excessão na Unissex?? @GregorySantos

**Comment by GregorySantos** [comment]
Acho que pode tratar na unissex mesmo, tipo se o Insert retornar 0 dá free no node criado. Mas não sei se é a melhor ideia.

**Comment by FormigTeen** [comment]
Beleza, vou criar uma função de delação de Node na sua List.h, beleza? Aí uso ela para deletar certinho...
