### ISSUE TITLE
Bug Detectado!!! Compatibilidade Compilador C++

### ISSUE THREAD

**Issue by FormigTeen** [GregorySantos/TrabEDA2017.1#70]
Palavra reservada new no programa... Trocar para newVar.

**Comment by LucasNBP** [comment]
não precisa, pois o professor especificou compilar no gcc -x, que é um compilador de c exclusivo, não precisamos nos preocupar o c++ se não quisermos

**Comment by FormigTeen** [comment]
Beleza...
