### ISSUE TITLE
Falha de Segmentação Bug!!! Lista

### ISSUE THREAD

**Issue by FormigTeen** [GregorySantos/TrabEDA2017.1#78]
Insira um Contato chamado Matheus Freitas

E mande procurar por Lucas Natanael

Encerramento Inesperado

**Comment by FormigTeen** [comment]
Ele funciona para alguns, para outros não. O que será que tem nesse caso?

**Comment by GregorySantos** [comment]
Isso é na lista ou na árvore?

**Comment by FormigTeen** [comment]
Na lista

**Comment by FormigTeen** [comment]
A Arvore ainda não tem o Insert implementado, parece que o problema está no primeiro nome... porque quando o primeiro nome é diferente causa problema sei lá...

**Comment by GregorySantos** [comment]
vou rodar aqui pra ver

**Comment by FormigTeen** [comment]
Huuum, está parecendo falha no if... de lógica, entre AND e OU

**Comment by FormigTeen** [comment]
Lá no While...https://github.com/GregorySantos/TrabEDA2017.1/blob/6d7b627c3702b0c460f40adc0f037356da66b11b/App/Headers/List.h#L138

**Comment by GregorySantos** [comment]
Eu pensei assim, enquanto nome **ou** sobrenome forem diferentes do procurado, **e** o próximo não é NULL, continua percorrendo a lista.
Se colocasse nome **e** sobrenome diferentes o while ia parar se um dos dois fosse igual.

**Comment by FormigTeen** [comment]
Enquanto ( Nome e Sobrenome são Diferentes ) ou Próximo é diferente de Null.

Não seria essa a lógica?

**Comment by FormigTeen** [comment]
Nesse seu caso, o ou tem que prevalecer mas na execução a precendência é do e aí ele faz isso...

Enquanto  ( o próximo não é Null e o sobrenome é diferente do procurado ) ou nome é diferente do procurado

**Comment by GregorySantos** [comment]
Não tá funcionando assim também

**Comment by FormigTeen** [comment]
Coloca sua lógica mas com os parentes no ou

**Comment by GregorySantos** [comment]
Já fiz isso, deu no mesmo.
O engraçado é que se procurar por um nome que está na lista funciona.

**Comment by FormigTeen** [comment]
Sim, ele sabe aonde parar quando acha igual... Mas não sabe quando parar quando não achar o nome

**Comment by FormigTeen** [comment]
Básicamente é esse o erro, tenho certeza que é no While

**Comment by GregorySantos** [comment]
acho que resolvi, vou mandar o PR
